name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  check-pull-request-title:
    name: Check Pull Request Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # For reading PR title
    steps:
      - name: Check Pull Request Title
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16 # v1.0.2
        with:
          allowed_prefixes: "feat: ,fix: ,bug: ,ci: ,refactor: ,docs: ,build: ,chore(,deps(,chore: ,feat!: ,fix!: ,refactor!: ,test: ,build(deps): " # title should start with the given prefix

  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write # For writing labels and comments on PRs
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@6c7614088c6e21fbd961044a78873e8755e389c1 # v2025.10.11.04
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
