name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  check-pull-request-title:
    name: Check Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: "feat: ,fix: ,bug: ,ci: ,refactor: ,docs: ,build: ,chore(,deps(,chore: ,feat!: ,fix!: ,refactor!: ,test: ,build(deps): " # title should start with the given prefix
