name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  check-pull-request-title:
    name: Check Pull Request Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check Pull Request Title
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16 # v1.0.2
        with:
          allowed_prefixes: "feat: ,fix: ,bug: ,ci: ,refactor: ,docs: ,build: ,chore(,deps(,chore: ,feat!: ,fix!: ,refactor!: ,test: ,build(deps): " # title should start with the given prefix

  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@c7b491eb600bdc990a92ee18b10e3e5b7c09212f # v2025.09.27.02
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
